version: '3'

services:
  api:
    build: .
    command: gunicorn --bind :8080 --workers 1 --threads 8 main:app --reload
#    volumes:
#      - ./src:/app
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Tokyo
    tty: true
